const os=require('os')

console.log(os.freemem())
console.log("the total memory is : ", os.totalmem())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.uptime())
console.log(os.platform())
console.log(os.release())
console.log(os.type())